SELECT MAX(SALARY) FROM hr.employees;

SELECT MAX(SALARY) - MIN(SALARY) FROM hr.employees;

SELECT JOB_ID, AVG(SALARY) FROM hr.employees
GROUP BY JOB_ID
ORDER BY 'salario_medio' DESC;

SELECT SUM(SALARY) FROM hr.employees;

SELECT MAX(ROUND(SALARY, 2)) as 'Maior Salário', MIN(ROUND(SALARY, 2)) as 'Menor Salário',
SUM(ROUND(SALARY, 2)) as 'Soma dos Salaŕios', ROUND(AVG(SALARY), 2) as 'Média dos Salários'
FROM hr.employees;

SELECT JOB_ID, COUNT(*) FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';

SELECT JOB_ID, AVG(SALARY) AS `Média Salarial` FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID <> 'IT_PROG'
ORDER BY `Média Salarial` DESC;

SELECT DEPARTMENT_ID, AVG(SALARY) AS `Média Salarial`, COUNT(*) AS `Número de Funcionários` FROM hr.employees
GROUP BY DEPARTMENT_ID
HAVING `Número de Funcionários`  > 10;

UPDATE hr.employees SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE('515%');

SELECT FIRST_NAME FROM hr.employees
WHERE LENGTH(FIRST_NAME) >= 8;

SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM hr.employees;

SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM hr.employees;

SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM hr.employees;

SELECT UCASE(FIRST_NAME) FROM hr.employees;

SELECT LAST_NAME, HIRE_DATE FROM hr.employees
WHERE MONTH(HIRE_DATE) = 07 AND YEAR(HIRE_DATE) = 1987;

SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) FROM hr.employees;